export const catalogo = [
{ id: 1, titulo: "Rocket League", categoria: "Deportes/Acción", anio: 2015, destacado: false ,urlFoto: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Rocket_League_coverart.jpg"},
{ id: 2, titulo: "Warframe", categoria: "Shooter/RPG", anio: 2013, destacado: true ,urlFoto: ""},
{ id: 3, titulo: "Jujutsu Kaisen", categoria: "Anime/Acción", anio: 2020, destacado: true ,urlFoto: ""},
{ id: 4, titulo: "Hollow Knight", categoria: "Aventura/Indie", anio: 2017, destacado: false ,urlFoto: ""},
{ id: 5, titulo: "Shingeki no Kyojin", categoria: "Anime/Drama", anio: 2013, destacado: true ,urlFoto: ""},
{ id: 6, titulo: "Minecraft", categoria: "Supervivencia", anio: 2011, destacado: false ,urlFoto: ""},
{ id: 7, titulo: "Boku no Hero Academia", categoria: "Anime/Acción", anio: 2016, destacado: true ,urlFoto: ""},
{ id: 8, titulo: "Elden Ring", categoria: "RPG/Acción", anio: 2022, destacado: true ,urlFoto: ""},
{ id: 9, titulo: "Nanatsu no Taizai", categoria: "Anime/Aventura", anio: 2014, destacado: false ,urlFoto: ""},
{ id: 10, titulo: "Stardew Valley", categoria: "Simulación/Indie", anio: 2016, destacado: true ,urlFoto: ""},
{ id: 11, titulo: "Kimetsu no Yaiba", categoria: "Anime/Acción", anio: 2019, destacado: true ,urlFoto: ""},
{ id: 12, titulo: "Cyberpunk 2077", categoria: "RPG/Mundo Abierto", anio: 2020, destacado: false ,urlFoto: ""},
{ id: 13, titulo: "Death Note", categoria: "Anime/Misterio", anio: 2006, destacado: true ,urlFoto: ""},
{ id: 14, titulo: "Red Dead Redemption 2", categoria: "Acción/Mundo Abierto", anio: 2018, destacado: true ,urlFoto: ""},
{ id: 15, titulo: "One Piece", categoria: "Anime/Aventura", anio: 1999, destacado: false ,urlFoto: ""},
{ id: 16, titulo: "Hades", categoria: "Roguelike/Indie", anio: 2020, destacado: true ,urlFoto: ""},
{ id: 17, titulo: "Naruto Shippuden", categoria: "Anime/Acción", anio: 2007, destacado: false ,urlFoto: ""},
{ id: 18, titulo: "The Legend of Zelda: Breath of the Wild", categoria: "Aventura", anio: 2017, destacado: true ,urlFoto: ""},
{ id: 19, titulo: "Fullmetal Alchemist: Brotherhood", categoria: "Anime/Aventura", anio: 2009, destacado: true ,urlFoto: ""},
{ id: 20, titulo: "God of War", categoria: "Acción/Aventura", anio: 2018, destacado: true ,urlFoto: ""},
{ id: 21, titulo: "Persona 5 Royal", categoria: "JRPG", anio: 2019, destacado: false ,urlFoto: ""},
{ id: 22, titulo: "Hunter x Hunter", categoria: "Anime/Aventura", anio: 2011, destacado: true ,urlFoto: ""},
{ id: 23, titulo: "League of Legends", categoria: "MOBA", anio: 2009, destacado: false ,urlFoto: ""},
{ id: 24, titulo: "Valorant", categoria: "Shooter Táctico", anio: 2020, destacado: false ,urlFoto: ""},
{ id: 25, titulo: "Steins;Gate", categoria: "Anime/Ciencia Ficción", anio: 2011, destacado: true ,urlFoto: ""},
{ id: 26, titulo: "The Witcher 3: Wild Hunt", categoria: "RPG/Aventura", anio: 2015, destacado: true ,urlFoto: ""},
{ id: 27, titulo: "Dragon Ball Z", categoria: "Anime/Acción", anio: 1989, destacado: true ,urlFoto: ""},
{ id: 28, titulo: "Celeste", categoria: "Plataformas/Indie", anio: 2018, destacado: false ,urlFoto: ""},
{ id: 29, titulo: "Portal 2", categoria: "Puzzles", anio: 2011, destacado: true ,urlFoto: ""},
{ id: 30, titulo: "Neon Genesis Evangelion", categoria: "Anime/Mecha", anio: 1995, destacado: true ,urlFoto: ""},
{ id: 31, titulo: "Apex Legends", categoria: "Battle Royale", anio: 2019, destacado: false ,urlFoto: ""},
{ id: 32, titulo: "Baldur's Gate 3", categoria: "RPG/Estrategia", anio: 2023, destacado: true ,urlFoto: ""},
{ id: 33, titulo: "Bloodborne", categoria: "RPG/Acción", anio: 2015, destacado: false ,urlFoto: ""},
{ id: 34, titulo: "Cowboy Bebop", categoria: "Anime/Ciencia Ficción", anio: 1998, destacado: true ,urlFoto: ""},
{ id: 35, titulo: "Terraria", categoria: "Supervivencia/Indie", anio: 2011, destacado: false ,urlFoto: ""}
];